// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns the top 20 newest posts.\nIMPORTANT: You must set the 'Accept: application/json' header to receive JSON.\nWithout this header, the server will default to serving the HTML template.",
                "produces": [
                    "application/json",
                    "text/html"
                ],
                "summary": "Search Aggregated Blogs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search Keyword (defaults to 'golang')",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved posts",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/logic.Post"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found: Only the root path '/' is supported",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "logic.Post": {
            "type": "object",
            "properties": {
                "published_at": {
                    "type": "string",
                    "example": "2026-01-21T10:00:00Z"
                },
                "source": {
                    "type": "string",
                    "example": "dev.to"
                },
                "title": {
                    "type": "string",
                    "example": "golang"
                },
                "url": {
                    "type": "string",
                    "example": "https://dev.to/user/post"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GRIP API",
	Description:      "A high-performance developer blog aggregator proxy.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
